export var assessmentObjects = [
  { assessment: 'interestProfilerSf', endurl: 'intro', title: 'ip_title', extra: '', color: 'blue', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'restore', 'Logout'] },
  { assessment: 'interestProfilerSf', endurl: 'assessment', title: 'ip_title', extra: '', color: 'blue', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'partialsave', 'startover', 'Logout'] },
  { assessment: 'interestProfilerSf', endurl: 'result', title: 'ip_title', extra: 'result', color: 'blue', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'resultsave','startover',  'print', 'Logout'] },
  { assessment: 'interestProfilerSf', endurl: 'occlist', title: 'ip_title', extra: 'occ_list', color: 'blue', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'startover', 'Logout'] },
  { assessment: 'interestProfilerSf', endurl: 'restore', title: 'ip_title', extra: 'btn_rst', color: 'blue', btnClass: 'btn-green-plp3', buttons: ['interestprofiler', 'Logout'] },
  { assessment: 'interestProfilerSf', endurl: 'occCareer', title: '', extra: '', color: '', btnClass: '', buttons: [] },
  { assessment: 'interestProfilerSf', endurl: 'occCluster', title: '', extra: '', color: '', btnClass: '', buttons: [] },
  { assessment: 'interestProfilerSf', endurl: 'occEmergCareer', title: '', extra: '', color: '', btnClass: '', buttons: [] },
  { assessment: 'interestProfilerSf', endurl: 'occIndex', title: '', extra: '', color: '', btnClass: '', buttons: [] },
   { assessment: 'interestProfilerSf', endurl: 'compare', title: '', extra: '', color: '', btnClass: '', buttons: []},
  { assessment: 'entrepreneurQuiz', endurl: 'intro', title: 'eq_title', extra: '', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'restore', 'Logout'] },
  { assessment: 'entrepreneurQuiz', endurl: 'assessment', title: 'eq_title', extra: '', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'partialsave','startover',  'Logout'] },
  { assessment: 'entrepreneurQuiz', endurl: 'result', title: 'eq_title', extra: 'result', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'resultsave','startover', 'print', 'Logout'] },
  { assessment: 'entrepreneurQuiz', endurl: 'restore', title: 'eq_title', extra: 'btn_rst', color: 'green', btnClass: 'btn-green-plp3', buttons: ['entrepreneur', 'Logout'] },
  { assessment: 'occSort', endurl: 'intro', title: 'os_title', extra: '', color: 'iris', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'restore', 'Logout'] },
  { assessment: 'occSort', endurl: 'factors', title: 'os_title', extra: 'select_prior_factor', color: 'iris', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'startover', 'Logout'] },
  { assessment: 'occSort', endurl: 'assessment', title: 'os_title', extra: '', color: 'iris', btnClass: 'btn-green-plp3', buttons: ['langbtn','partialsave', 'startover', 'Logout'] },
  { assessment: 'occSort', endurl: 'compare', title: 'os_title', extra: '', color: 'iris', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'startover','Logout']},
  { assessment: 'occSort', endurl: 'result', title: 'os_title', extra: 'result', color: 'iris', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'resultsave','startover', 'print', 'Logout'] },
  { assessment: 'occSort', endurl: 'restore', title: 'os_title', extra: 'btn_rst', color: 'green', btnClass: 'btn-green-plp3', buttons: ['occSort', 'Logout'] },
  { assessment: 'occSort', endurl: 'comparison', title: 'os_title', extra: 'occ_list', color: 'iris', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'resultsave','startover','Logout'] },
  { assessment: 'occSort', endurl: 'occCareer', title: '', extra: '', color: '', btnClass: '', buttons: [] },
  { assessment: 'occSort', endurl: 'occCluster', title: 'os_title', extra: 'occ_list', color: 'iris', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'startover','Logout'] },
  { assessment: 'occSort', endurl: 'occEmergCareer', title: 'os_title', extra: 'occ_list', color: 'iris', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'startover','Logout'] },
  { assessment: 'occSort', endurl: 'occIndex', title: '', extra: '', color: '', btnClass: '', buttons: [] },
  { assessment: 'cciJr', endurl: 'intro', title: 'cci_title', extra: '', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'restore', 'Logout'] },
  { assessment: 'cciJr', endurl: 'assessment', title: 'cci_title', extra: '', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'partialsave', 'startover', 'Logout'] },
  { assessment: 'cciJr', endurl: 'result', title: 'cci_title', extra: 'entrp_score_name', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'resultsave', 'startover', 'print', 'Logout'] },
  { assessment: 'cciJr', endurl: 'restore', title: 'cci_title', extra: 'btn_rst', color: 'green', btnClass: 'btn-green-plp3', buttons: ['cciJr', 'Logout'] },
   { assessment: 'cciAdult', endurl: 'intro', title: 'cci_title', extra: '', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'restore', 'Logout'] },
  { assessment: 'cciAdult', endurl: 'assessment', title: 'cci_title', extra: '', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'partialsave', 'startover', 'Logout'] },
  { assessment: 'cciAdult', endurl: 'result', title: 'cci_title', extra: 'entrp_score_name', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'resultsave', 'startover', 'print', 'Logout'] },
  { assessment: 'cciAdult', endurl: 'restore', title: 'cci_title', extra: 'btn_rst', color: 'green', btnClass: 'btn-green-plp3', buttons: ['cciJr', 'Logout'] },
 
  
   { assessment: 'lssAsessment', endurl: 'intro', title: 'lss_title', extra: '', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'restore', 'Logout'] },
  { assessment: 'lssAsessment', endurl: 'assessment', title: 'lss_title', extra: '', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'partialsave', 'startover', 'Logout'] },
  { assessment: 'lssAsessment', endurl: 'result', title: 'lss_title', extra: 'entrp_score_name', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'resultsave', 'startover', 'print', 'Logout'] },
  { assessment: 'lssAsessment', endurl: 'restore', title: 'lss_title', extra: 'btn_rst', color: 'green', btnClass: 'btn-green-plp3', buttons: ['Learning Style Survey', 'Logout'] },
  { assessment: 'wesAsessment', endurl: 'intro', title: 'wes_title', extra: '', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'restore', 'Logout'] },
  { assessment: 'wesAsessment', endurl: 'assessment', title: 'wes_title', extra: '', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'partialsave', 'startover', 'Logout'] },
  { assessment: 'wesAsessment', endurl: 'result', title: 'wes_title', extra: 'result', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'resultsave', 'startover', 'print', 'Logout'] },
  { assessment: 'wesAsessment', endurl: 'restore', title: 'wes_title', extra: 'btn_rst', color: 'green', btnClass: 'btn-green-plp3', buttons: ['wes', 'Logout'] },
 { assessment: 'wilAsessment', endurl: 'intro', title: 'wil_title', extra: '', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'restore', 'Logout'] },
  { assessment: 'wilAsessment', endurl: 'assessment', title: 'wil_title', extra: '', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'partialsave', 'startover', 'Logout'] },
  { assessment: 'wilAsessment', endurl: 'result', title: 'wil_title', extra: 'result', color: 'green', btnClass: 'btn-green-plp3', buttons: ['langbtn', 'resultsave', 'startover', 'print', 'Logout'] },
  { assessment: 'wilAsessment', endurl: 'restore', title: 'wil_title', extra: 'btn_rst', color: 'green', btnClass: 'btn-green-plp3', buttons: ['wes', 'Logout'] },
];

export var pieColors = 
{ "conventional": "#e57373", "artistic": "#6fa301",
 "realistic": "#01ae83", "investigative": "#00346d", 
 "social": "#b0006c", "enterprising": "#0c8cbd" };

export var pieIpIcons = {"conventional":'/assets/images/conventional.png',"artistic":'/assets/images/artistic.png',
    "realistic":'/assets/images/realistic.png',"investigative":'/assets/images/investigative.png',
"social":'/assets/images/social.png',"enterprising":'/assets/images/enterprise.png'}; 
export var clusterDetails = [
  { clusterName: 'Agriculture, Food, and Natural Resources', clusterIconValue: 'icon-clu_agriculture', clusterId: '110100', clusterBgColor:'#47bf2a' },
  { clusterName: 'Architecture and Construction', clusterIconValue: 'icon-clu_architecture', clusterId: '110200', clusterBgColor:'#6c777e'  },
  { clusterName: 'Arts, Audio/Visual Technology, and Communications', clusterIconValue: 'icon-clu_arts', clusterId: '110300', clusterBgColor:'#ffa100'  },
  { clusterName: 'Business Management and Administration', clusterIconValue: 'icon-clu_business', clusterId: '110400', clusterBgColor:'#003eb6'  },
  { clusterName: 'Education and Training', clusterIconValue: 'icon-clu_education_and_training', clusterId: '110500', clusterBgColor:'#00b7c3'  },
  { clusterName: 'Finance', clusterIconValue: 'icon-clu_finance', clusterId: '110600', clusterBgColor:'#ef3f42'  },
  { clusterName: 'Government and Public Administration', clusterIconValue: 'icon-clu_government', clusterId: '110700', clusterBgColor:'#00ad83'  },
  { clusterName: 'Health Science', clusterIconValue: 'icon-clu_health_science', clusterId: '110800', clusterBgColor:'#af006b'  },
  { clusterName: 'Hospitality and Tourism', clusterIconValue: 'icon-clu_hospitality_and_tourism', clusterId: '110900', clusterBgColor:'#e0119d'  },
  { clusterName: 'Human Services', clusterIconValue: 'icon-clu_human_services', clusterId: '111000', clusterBgColor:'#88cc2a'  },
  { clusterName: 'Information Technology', clusterIconValue: 'icon-clu_information_technology', clusterId: '111100', clusterBgColor:'#b4d600'  },
  { clusterName: 'Law, Public Safety, Corrections, and Security', clusterIconValue: 'icon-clu_law', clusterId: '111200', clusterBgColor:'#949ca1'  },
  { clusterName: 'Manufacturing', clusterIconValue: 'icon-clu_manufacturing', clusterId: '111300', clusterBgColor:'#7700b8'  },
  { clusterName: 'Marketing', clusterIconValue: 'icon-clu_marketing', clusterId: '111400', clusterBgColor:'#af00b8'  },
  { clusterName: 'Science, Technology, Engineering, and Mathematics', clusterIconValue: 'icon-clu_science_technology', clusterId: '111500', clusterBgColor:'#fdcc2f'  },
  { clusterName: 'Transportation, Distribution, and Logistics', clusterIconValue: 'icon-clu_transportation_distribution_and_logistics', clusterId: '111600', clusterBgColor:'#ff7900'  }];