version: "3"

services:
    cis-mobile:
        env_file:
            - .env
        tty: false
        image: intocareers/cis-mobile        
        container_name: cis-mobile
        build:
            context: .
        ports:
            - "${DOCKER_PORT}:3000"
        volumes:
            - ./server:/usr/app/
            - ./dist:/usr/dist             
            - /usr/app/node_modules
        restart: always